# 应用配置
spring.application.name=SmartCampusLifeServer

## MySQL 数据库配置
#spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus_life?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#spring.datasource.username=root
#spring.datasource.password=Housizhe3534
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA 配置
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
## 关闭 Spring Security
#spring.security.enabled=false
